name: vibration_service_example
description: Example app for the vibration_service package.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  vibration_service:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
